#!/bin/sh

SERVICE_NAME="usb-gadget"

start() {
        printf 'Starting %s: ' "$SERVICE_NAME"
        mkdir -pv /var/config
        set -e
        mount -t configfs none /var/config
        CWD=`pwd`
        cd /var/config/usb_gadget
        mkdir g
        cd g
        echo 0x1d6b > idVendor
        echo 0x0104 > idProduct
        echo 0x0100 > bcdDevice
        echo 0x0200 > bcdUSB
        mkdir strings/0x409
        echo "fccabedf00115599" > strings/0x409/serialnumber
        echo "luhui"            > strings/0x409/manufacturer
        echo "AUTOTYPE OVER USB" > strings/0x409/product
        mkdir -p functions/hid.usb0
        echo 1 > functions/hid.usb0/protocol
        echo 1 > functions/hid.usb0/subclass
        echo 8 > functions/hid.usb0/report_length
        echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/hid.usb0/report_desc
        mkdir -p functions/rndis.usb0  # network
        mkdir -p configs/c.1
        echo 1000 > configs/c.1/MaxPower
        ln -s functions/rndis.usb0 configs/c.1/
        ln -s functions/hid.usb0   configs/c.1/
        echo 20980000.usb > UDC
        cd $CWD
}

case "$1" in
        start)
                "$1";;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac

