#!/bin/sh

PIDFILE="/var/run/wpa-supplicant-wlan0.pid"

case "$1" in
  start)
        printf "Starting wpa-supplicant: "
        wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf -B -P $PIDFILE && echo "OK" || echo "FAIL"
        ;;
  stop)
        printf "Stopping wpa-supplicant: "
        kill `cat $PIDFILE` && echo "OK" || echo "FAIL"
        ;;
  restart|reload)
        "$0" stop
        sleep 1
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
