#!/bin/sh

SERVICE_NAME="static-ip-usb0"

start() {
	printf 'Starting %s: ' "$SERVICE_NAME"
	ifconfig usb0 up
	ifconfig usb0 add 192.168.99.2
}

case "$1" in
	start)
		"$1";;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
