#!/bin/sh

SERVICE_NAME="alsaucm"
START_COMMAND="alsaucm -c chtmax98090 set _verb HiFi"

start() {
	printf 'Starting %s: ' "$SERVICE_NAME"
	$START_COMMAND
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}


case "$1" in
	start)
		"$1";;
	*)
		echo "Usage: $0 {start}"
		exit 1
esac
